package:
  format-version: "1.0.0"
  name: "smartenergy_metersandmore_apps"
  version: "v1.1.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy_metersandmore"
      type: "package"
      version: "v1.1.0"
    - name: "shd"
      type: "package"
      version: "v1.1.0"
